from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-21 19:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ("catalog", "0002_draft_cost"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="variant_group",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
