from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-21 20:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ("catalog", "0003_product_attributes_product_description_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="product",
            name="showcase",
            field=models.BooleanField(
                default=False,
                help_text="Display a non-purchasable preview while stock and pricing setup is completed.",
            ),
        ),
    ]
