from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-23 13:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('businesses', '0003_shop_details'),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name='business',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
