from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-23 14:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('businesses', '0004_business_suspended'),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('published', False), ('suspended', True)), _connector='OR'), name='deleted_shop_disabled'),
        ),
    ]
