"use client";
import { useFeedback } from "../../lib/feedback";

import { useCallback, useEffect, useRef, useState } from "react";
import { api, money, type Order, type Product, type Sale } from "@/lib/api";
import { definiteRejection } from "@/lib/order-attempt";
import { ActionIcon, Avatar, EditorDialog } from "./Users";
import CatalogManager from "../dashboard/CatalogManager";
import ImageField from "../dashboard/ImageField";
import Icon from "@/components/Icon";
import { Feedback, Pager, allPages, formData, useAction, useData, type Page, type Shop } from "./shared";

const tabs = ["Details", "Access", "Catalog", "Orders", "Sales", "Stock", "Movements"] as const;
export default function PlatformShop({ id, userId, onBack }: { id: number; userId: number; onBack: () => void }) {
  const state = useData<Shop>(`platform/shops/${id}/`);
  const [tab, setTab] = useState<typeof tabs[number]>("Details"), [branch, setBranch] = useState<number>();
  const shop = state.data;
  const selected = shop?.branches?.some(b => b.id === branch) ? branch : shop?.branches?.[0]?.id;
  const icons: Record<string, string> = { Details: "Settings", Access: "Team", Catalog: "Catalog", Orders: "Orders", Sales: "Sales", Stock: "Inventory", Movements: "Operations" };
  const descriptions: Record<string, string> = { Details: "Storefront, delivery and branch settings.", Access: "People, roles and branch permissions.", Catalog: "Products, variants and categories.", Orders: "Review and fulfil customer orders.", Sales: "Completed sales, payments and refunds.", Stock: "On-hand quantities and reserved inventory.", Movements: "A history of stock changes in this branch." };
  return <section className="shop-admin"><nav className="shop-admin-breadcrumb" aria-label="Shop breadcrumb"><button className="secondary" onClick={onBack}><Icon name="left" />Back to shops</button><span aria-hidden="true">/</span><span>{shop?.name || "Loading shop…"}</span></nav><Feedback {...state} />{shop && <>
    <header className="shop-admin-heading"><div><h1>{shop.name}</h1><p>/{shop.slug} · {shop.owners.join(", ") || "No active owner"}</p></div><span className={`shop-state ${shop.suspended ? "is-paused" : shop.published ? "is-published" : ""}`}>{shop.suspended ? "Suspended" : shop.published ? "Published" : "Draft"}</span></header>
    <nav aria-label="Shop administration" className="shop-section-nav">{tabs.map(name => <button key={name} aria-current={tab === name ? "page" : undefined} className={tab === name ? "active" : "secondary"} onClick={() => setTab(name)}><Icon name={icons[name]} /><span>{name}</span></button>)}</nav>
    <div className="shop-section-context"><div><span className="eyebrow">{tab}</span><p>{descriptions[tab]}</p></div>{!["Details", "Access"].includes(tab) && <label className="shop-branch">Working branch<select value={selected ?? ""} onChange={e => setBranch(Number(e.target.value))}>{shop.branches?.map(b => <option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}</div>
    <div className={`shop-tab-content shop-tab-${tab.toLowerCase()}`}>
    {tab === "Details" && <Details shop={shop} reload={state.reload} onDeleted={onBack} />}
    {tab === "Access" && <Access shop={shop} />}
    {!["Details", "Access"].includes(tab) && (selected ? tab === "Catalog" ? <Catalog key={`${id}:${selected}`} shop={shop} branch={selected} /> : <Records key={`${id}:${selected}:${tab}`} shop={shop} branch={selected} userId={userId} resource={tab.toLowerCase()} /> : <p>Create a branch in Details to manage this shop.</p>)}
    </div>
  </>}</section>;
}

function Details({ shop, reload, onDeleted }: { shop: Shop; reload: () => Promise<void>; onDeleted: () => void }) {
  const [confirmSlug, setConfirmSlug] = useState("");
  const action = useAction(); const base = `platform/shops/${shop.id}/`;
  return <div className="shop-details-grid"><Feedback {...action} /><section className="panel shop-visibility"><h2>Shop visibility</h2><p>Hiding removes this shop from the marketplace and prevents new customer orders. Staff can still manage the shop and fulfil existing orders.</p><button disabled={action.busy || shop.suspended} onClick={() => void action.run(async () => { await api(base, { published: !shop.published }, "PATCH"); await reload(); }, shop.published ? "Shop hidden from customers" : "Shop shown in marketplace")}>{shop.published ? "Hide shop" : "Show shop"}</button>{shop.suspended && <p>Remove the suspension before showing this shop.</p>}</section><form className="panel form-grid shop-profile-form" key={JSON.stringify(shop)} onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void action.run(async () => { await api(base, { ...d, published: d.published === "on", suspended: d.suspended === "on", delivery_enabled: d.delivery_enabled === "on", delivery_fee: Number(d.delivery_fee), safety_buffer: Number(d.safety_buffer), storefront_branch: d.storefront_branch ? Number(d.storefront_branch) : null }, "PATCH"); await reload(); }, "Shop details saved"); }}>
    <h2>Shop details</h2>{(["name", "slug", "contact", "website", "timezone"] as const).map(name => <label key={name}>{name === "name" ? "Shop name" : name === "slug" ? "Shop URL name" : name[0].toUpperCase() + name.slice(1)}<input name={name} defaultValue={shop[name]} required={["name", "slug", "timezone"].includes(name)} type={name === "website" ? "url" : "text"} /></label>)}<label>Description<textarea name="description" defaultValue={shop.description} maxLength={2000} /></label><ImageField businessId={shop.id} name="logo" initial={shop.logo} uploadEndpoint={base + "images/"} /><label>Currency<input readOnly value={shop.currency} /></label><label>Delivery fee<input name="delivery_fee" type="number" min={0} defaultValue={shop.delivery_fee} required /></label><label>Safety buffer<input name="safety_buffer" type="number" min={0} defaultValue={shop.safety_buffer} required /></label><label>Online fulfilment branch<select name="storefront_branch" defaultValue={shop.storefront_branch ?? ""}><option value="">First branch</option>{shop.branches?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="check"><input type="checkbox" name="delivery_enabled" defaultChecked={shop.delivery_enabled} />Enable delivery</label><label className="check"><input type="checkbox" name="published" defaultChecked={shop.published} />Publish storefront</label><label className="check"><input type="checkbox" name="suspended" defaultChecked={shop.suspended} />Suspend shop access and new orders</label><button disabled={action.busy}>Save shop details</button></form>
    <section className="panel shop-branches"><h2>Branches</h2>{shop.branches?.map(b => <form key={`${b.id}:${b.name}`} className="platform-search" onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void action.run(async () => { await api(base + `branches/${b.id}/`, d, "PATCH"); await reload(); }, "Branch renamed"); }}><label>Branch {b.id} name<input name="name" required maxLength={100} defaultValue={b.name} /></label><button disabled={action.busy}>Rename branch {b.id}</button></form>)}<form className="platform-search" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = formData(form); void action.run(async () => { await api(base + "branches/", d); await reload(); form.reset(); }, "Branch created"); }}><label>New branch name<input name="name" required maxLength={100} /></label><button disabled={action.busy}>Add branch</button></form></section>
    <details className="panel shop-danger"><summary>Delete shop</summary><p>Remove this shop from the portal and marketplace and disable staff access. Orders, sales and audit history are retained for record keeping. The shop URL stays reserved. Complete or cancel outstanding orders first.</p><form className="form-grid" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api(base, { confirm_slug: confirmSlug }, "DELETE"); onDeleted(); }); }}><label>Type {shop.slug} to confirm deletion<input value={confirmSlug} onChange={e => setConfirmSlug(e.target.value)} autoComplete="off" required /></label><button disabled={action.busy || confirmSlug !== shop.slug}>Delete shop</button></form></details>
  </div>;
}

type AccessRow = { first_name: string; last_name: string; photo?: string; id: number; username: string; role: string; branch: number; active: boolean };
function Access({ shop }: { shop: Shop }) {
  const [page, setPage] = useState(1), [editing, setEditing] = useState<AccessRow | "new">();
  const base = `platform/shops/${shop.id}/access/`;
  const state = useData<Page<AccessRow>>(base + `?page=${page}`), action = useAction();
  const row = editing && editing !== "new" ? editing : undefined;
  return <><header className="people-heading"><div><span className="eyebrow">SHOP TEAM</span><h2>Shop access</h2><p>Give each person the right role and branch. Keep at least one active owner.</p></div><button onClick={() => setEditing("new")}><ActionIcon kind="add" />Assign shop access</button></header><Feedback {...action} /><Feedback {...state} /><section className="people-directory"><div className="platform-table"><table className="people-table"><thead><tr><th>Person</th><th>Role</th><th>Branch</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.data?.results.map(m => <tr key={m.id}><td><div className="person-identity"><Avatar user={m} /><strong>{m.username}</strong></div></td><td><span className="person-badge">{m.role}</span></td><td>{shop.branches?.find(b => b.id === m.branch)?.name}</td><td><span className={`person-status ${m.active ? "is-active" : ""}`}><i />{m.active ? "Active" : "Inactive"}</span></td><td><div className="person-row-actions"><button className="person-icon" aria-label={`Edit access for ${m.username}`} onClick={() => setEditing(m)}><ActionIcon kind="edit" /></button><button className="person-icon danger" aria-label={`Delete access for ${m.username}`} disabled={action.busy} onClick={() => { if (window.confirm(`Remove ${m.username}'s access to ${shop.name}? Their account and other shop roles remain.`)) void action.run(async () => { await api(base + m.id + "/", undefined, "DELETE"); if (page > 1) setPage(1); else await state.reload(); }, "Shop access removed"); }}><ActionIcon kind="delete" /></button></div></td></tr>)}</tbody></table></div>{state.data?.count === 0 && <p className="people-empty">No shop members yet.</p>}<Pager data={state.data} page={page} setPage={setPage} /></section>
    {editing && <EditorDialog title={row ? `Edit access for ${row.username}` : "Assign shop access"} onClose={() => setEditing(undefined)}><form className="person-form" onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void action.run(async () => { await api(base + (row ? row.id + "/" : ""), { ...d, branch: Number(d.branch), active: d.active === "on" }, row ? "PATCH" : "POST"); await state.reload(); setEditing(undefined); }, "Shop access saved"); }}><Feedback {...action} />{!row && <label>Existing username<input name="username" required /></label>}<div className="person-fields"><label>Shop role<select name="role" defaultValue={row?.role ?? "cashier"}><option value="owner">Owner</option><option value="manager">Manager</option><option value="cashier">Cashier</option></select></label><label>Assigned branch<select name="branch" defaultValue={row?.branch ?? shop.branches?.[0]?.id}>{shop.branches?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><label className="check"><input name="active" type="checkbox" defaultChecked={row?.active ?? true} />Access active</label><footer><button disabled={action.busy}>{row ? "Save shop access" : "Assign shop access"}</button></footer></form></EditorDialog>}
  </>;
}

type Category = { id: number; name: string };
function Catalog({ shop, branch }: { shop: Shop; branch: number }) {
  const base = `platform/shops/${shop.id}/branches/${branch}/`;
  const [products, setProducts] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [loading, setLoading] = useState(true), [error, setError] = useFeedback("error");
  const generation = useRef(0); const action = useAction();
  const reload = useCallback(async () => {
    const id = ++generation.current; setLoading(true); setError("");
    try { const [p, c] = await Promise.all([allPages<Product>(base + "products/"), allPages<Category>(base + "categories/")]); if (id === generation.current) { setProducts(p); setCategories(c); } }
    catch (e) { if (id === generation.current) setError((e as Error).message); }
    finally { if (id === generation.current) setLoading(false); }
  }, [base, setError]);
  useEffect(() => { const counter = generation; void reload(); return () => { counter.current++; }; }, [reload]);
  return <><Feedback error={error} loading={loading} /><Feedback {...action} />{!loading && !error && <CatalogManager businessId={shop.id} currency={shop.currency} products={products} categories={categories} reload={reload} apiBase={base} uploadEndpoint={`platform/shops/${shop.id}/images/`} />}
    <details className="panel"><summary>Manage categories</summary><form className="platform-search" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, d = formData(form); void action.run(async () => { await api(base + "categories/", d); await reload(); form.reset(); }, "Category created"); }}><label>New category name<input name="name" required maxLength={80} /></label><button disabled={action.busy}>Add category</button></form>{categories.map(c => <form className="platform-search" key={`${c.id}:${c.name}`} onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void action.run(async () => { await api(base + `categories/${c.id}/`, d, "PATCH"); await reload(); }); }}><label>Category {c.id}<input name="name" defaultValue={c.name} required maxLength={80} /></label><button disabled={action.busy}>Rename category {c.id}</button><button type="button" className="secondary" disabled={action.busy} onClick={() => { if (window.confirm(`Delete category “${c.name}”? Products must be moved out first.`)) void action.run(async () => { await api(base + `categories/${c.id}/`, undefined, "DELETE"); await reload(); }, "Category deleted"); }}>Delete category {c.id}</button></form>)}</details>
  </>;
}

type Attempt = { path: string; body: Record<string, unknown> };
type StockRow = { id: number; product: number; name: string; quantity: number; reserved: number };
type MovementRow = { id: number; stock__product__name: string; delta: number; reason: string; created_at: string };
type SaleRow = Sale & { returned: { id: number; amount: number; reason: string; method: string; reference: string }[] };
function StockProduct({ base }: { base: string }) {
  const [query, setQuery] = useState("");
  const state = useData<Page<Product>>(base + `products/?q=${encodeURIComponent(query)}`);
  return <><label>Find stock product<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name or SKU" /></label><label>Stock product<select name="product" required key={query} defaultValue=""><option value="" disabled>Select a product</option>{state.data?.results.map(p => <option key={p.id} value={p.id}>{p.name} · {p.sku} (#{p.id})</option>)}</select></label><Feedback error={state.error} />{state.data?.next && <p>Showing the first 50 matches. Narrow the search to find your product.</p>}</>;
}
function Records({ shop, branch, userId, resource }: { shop: Shop; branch: number; userId: number; resource: string }) {
  const base = `platform/shops/${shop.id}/branches/${branch}/`, key = `duukayo-platform-command:${userId}:${shop.id}:${branch}`;
  const [page, setPage] = useState(1), [revision, setRevision] = useState(0);
  const state = useData<Page<Order | SaleRow | StockRow | MovementRow>>(base + resource + `/?page=${page}`, revision);
  const [pending, setPending] = useState<Attempt | null>(null), [storageError, setStorageError] = useState("");
  const action = useAction();
  useEffect(() => {
    try { const raw = localStorage.getItem(key); if (raw) { const item = JSON.parse(raw); if (!item.path?.startsWith(base) || !item.body || typeof item.body !== "object") throw new Error(); setPending(item); } }
    catch { setStorageError("The saved operation cannot be read. Resolve it with support before recording another operation."); }
  }, [base, key]);
  async function command(path: string, body: Record<string, unknown>, retry = false) {
    if (storageError || (pending && !retry)) return;
    const attempt = retry && pending ? pending : { path, body: { ...body, client_id: crypto.randomUUID() } };
    await action.run(async () => {
      localStorage.setItem(key, JSON.stringify(attempt)); setPending(attempt);
      try { await api(attempt.path, attempt.body); }
      catch (e) { if (definiteRejection(e)) { localStorage.removeItem(key); setPending(null); } throw e; }
      localStorage.removeItem(key); setPending(null); setRevision(v => v + 1);
    }, "Operation recorded");
  }
  const disabled = action.busy || !!pending || !!storageError;
  const payments = <><label>Payment method<select name="method"><option value="cash">Cash</option><option value="manual_mtn">Manual MTN</option><option value="manual_airtel">Manual Airtel</option></select></label><label>Payment reference<input name="reference" maxLength={100} /></label></>;
  return <><h2>{resource[0].toUpperCase() + resource.slice(1)}</h2><Feedback {...action} /><Feedback error={storageError} /><Feedback {...state} />{pending && <section className="notice"><p>An operation needs confirmation. Retry its saved request before recording another change.</p><button disabled={action.busy} onClick={() => void command(pending.path, pending.body, true)}>Retry saved operation</button></section>}
    {resource === "stock" && <form className="panel form-grid" onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void command(base + "stock/adjust/", { ...d, product: Number(d.product), delta: Number(d.delta) }); }}><h3>Record stock movement</h3><StockProduct base={base} /><label>Movement type<select name="kind"><option value="receipt">Receipt</option><option value="opening">Opening stock</option><option value="adjustment">Adjustment</option></select></label><label>Quantity change<input name="delta" type="number" required min={-10000000} max={10000000} /></label><label>Reason<input name="reason" required minLength={3} maxLength={200} /></label><p>Use a negative quantity for a reduction. Reserved stock cannot be consumed by an adjustment.</p><button disabled={disabled}>Record stock movement</button></form>}
    {resource === "orders" && (state.data?.results as Order[] | undefined)?.map(order => <section className="panel" key={order.id}><h3>Order #{order.id} · {order.status}</h3><p>{order.name} · {order.phone} · {money(order.total, order.currency)}</p><p>{order.delivery ? order.address : "Pickup"} · Payment: {order.payment_state}</p><ul>{order.lines.map((line, i) => <li key={i}>{line.name} × {line.quantity}</li>)}</ul>{!["completed", "cancelled"].includes(order.status) && <form className="form-grid" onSubmit={e => { e.preventDefault(); void command(base + `orders/${order.id}/`, formData(e.currentTarget)); }}><label>Next status<select name="status">{({ pending: ["accepted", "cancelled"], accepted: ["preparing", "cancelled"], preparing: ["ready", "cancelled"], ready: ["completed", "cancelled"] }[order.status] || []).map(status => <option key={status}>{status}</option>)}</select></label>{payments}<button disabled={disabled}>Update order #{order.id}</button></form>}</section>)}
    {resource === "sales" && (state.data?.results as SaleRow[] | undefined)?.map(sale => <details className="panel" key={sale.id}><summary>Sale #{sale.id} · {money(sale.total, sale.currency)} · {new Date(sale.occurred_at).toLocaleString()}</summary><p>Recorded payment: {sale.payment.method} · Reference: {sale.payment.reference || "—"}</p>{sale.allocations?.map((part, i) => <p key={i}>{part.method}: {money(part.amount, sale.currency)} · {part.reference || "No reference"}</p>)}<p>Review flags: {sale.review_reasons.join(", ") || "None"}</p><ul>{sale.lines.map(line => <li key={line.id}>{line.name} × {line.quantity} · {money(line.price, sale.currency)}</li>)}</ul>{sale.returned.map(row => <p key={row.id}>Return #{row.id}: {money(row.amount, sale.currency)} · {row.reason} · {row.method}</p>)}<form className="form-grid" onSubmit={e => { e.preventDefault(); const d = formData(e.currentTarget); void command(base + `sales/${sale.id}/returns/`, { reason: d.reason, method: d.method, reference: d.reference, lines: [{ line: Number(d.line), quantity: Number(d.quantity), restock: d.restock === "on" }] }); }}><h3>Record return and refund</h3><label>Sale item<select name="line">{sale.lines.map(line => <option value={line.id} key={line.id}>{line.name} — sold {line.quantity}</option>)}</select></label><label>Return quantity<input name="quantity" type="number" min={1} max={10000} required /></label><label>Return reason<input name="reason" required minLength={3} maxLength={250} /></label>{payments}<label className="check"><input name="restock" type="checkbox" defaultChecked />Return items to stock</label><p>This records a refund already handled by the shop. It does not send money through a payment provider.</p><button disabled={disabled}>Record refund for sale #{sale.id}</button></form></details>)}
    {(resource === "stock" || resource === "movements") && <div className="platform-table stock-table" tabIndex={0} role="region" aria-label={resource === "stock" ? "Stock records" : "Stock movements"}><table><thead><tr>{(resource === "stock" ? ["Product ID", "Product", "Quantity", "Reserved"] : ["Product", "Change", "Reason", "Time"]).map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{resource === "stock" ? (state.data?.results as StockRow[] | undefined)?.map(row => <tr key={row.id}><td>{row.product}</td><td>{row.name}</td><td>{row.quantity}</td><td>{row.reserved}</td></tr>) : (state.data?.results as MovementRow[] | undefined)?.map(row => <tr key={row.id}><td>{row.stock__product__name}</td><td>{row.delta}</td><td>{row.reason}</td><td>{new Date(row.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}
    {state.data?.count === 0 && <div className="management-empty"><Icon name={resource === "stock" ? "Inventory" : resource === "movements" ? "Operations" : resource === "sales" ? "Sales" : "Orders"} /><h3>No {resource} yet</h3><p>Records for this branch will appear here.</p></div>}<Pager data={state.data} page={page} setPage={setPage} /></>;
}
