"use client";
import Image from "next/image";
import Icon from "@/components/Icon";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { api, type Profile } from "@/lib/api";
import ImageField from "../dashboard/ImageField";
import { allPages, Feedback, formData, Pager, useAction, useData, type Page, type Shop, type ShopAccess, type User } from "./shared";

export function ActionIcon({ kind }: { kind: "edit" | "delete" | "add" }) {
  return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind === "edit" ? <><path d="m16 3 5 5-12 12-6 1 1-6Z" /><path d="m14 5 5 5" /></> : kind === "delete" ? <><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7" /></> : <path d="M12 5v14M5 12h14" />}</svg>;
}

export function Avatar({ user }: { user: Pick<User, "username" | "first_name" | "last_name" | "photo"> }) {
  const [failed, setFailed] = useState(false);
  return <span className="person-avatar">{user.photo && !failed ? <Image unoptimized width={44} height={44} src={user.photo} alt="" onError={() => setFailed(true)} /> : (user.first_name?.[0] || user.username[0]) + (user.last_name?.[0] || "")}</span>;
}

export function EditorDialog({ title, onClose, children, eyebrow = "PEOPLE & PERMISSIONS" }: { title: string; onClose: () => void; children: ReactNode; eyebrow?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const element = ref.current; element?.showModal(); return () => element?.close(); }, []);
  return <dialog ref={ref} className="person-dialog" aria-label={title} onCancel={e => { e.preventDefault(); onClose(); }}><div className="dialog-toast-host" data-toast-host /><header><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button type="button" className="person-icon" aria-label="Close editor" onClick={onClose}>×</button></header>{children}</dialog>;
}

function UserForm({ user, profile, onSaved }: { user: User; profile: Profile; onSaved: () => Promise<void> }) {
  const action = useAction();
  const [shops, setShops] = useState<Shop[]>([]), [shopError, setShopError] = useState("");
  const [access, setAccess] = useState<ShopAccess[]>(user?.shop_access || []);
  const [changedAccess, setChangedAccess] = useState<number[]>([]);
  const [newShop, setNewShop] = useState("");
  useEffect(() => { let live = true; void allPages<Shop>("platform/shops/").then(rows => { if (live) setShops(rows); }).catch(e => { if (live) setShopError(e.message); }); return () => { live = false; }; }, []);
  const protectedUser = !!user && (user.is_staff || user.platform_admin || user.is_superuser) && !profile.can_manage_admins;
  function updateAccess(index: number, patch: Partial<ShopAccess>) { setAccess(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row)); setChangedAccess(ids => [...ids, access[index].business]); }
  return <form className="person-form" onSubmit={e => {
    e.preventDefault(); const data = formData(e.currentTarget);
    const body: Record<string, unknown> = { ...data, is_active: data.is_active === "on", shop_access: access.filter(row => changedAccess.includes(row.business)).map(({ business, branch, role, active }) => ({ business, branch, role, active })) };
    if (profile.can_manage_admins && !user?.is_superuser) body.platform_admin = data.platform_admin === "on";
    void action.run(async () => { await api(`platform/users/${user.id}/`, body, "PATCH"); await onSaved(); });
  }}><Feedback {...action} /><fieldset disabled={protectedUser || action.busy}>
    <section><h3>Personal details</h3><p>A familiar face and the right contact details help your team stay connected.</p><ImageField businessId={0} name="photo" initial={user?.photo} uploadEndpoint="platform/users/photos/" /><div className="person-fields"><label>First name<input name="first_name" defaultValue={user?.first_name} maxLength={150} autoComplete="given-name" /></label><label>Last name<input name="last_name" defaultValue={user?.last_name} maxLength={150} autoComplete="family-name" /></label><label>Email<input type="email" value={user.email} readOnly aria-describedby="identity-help" /></label><label>Phone number<input name="phone" type="tel" defaultValue={user?.phone} maxLength={40} autoComplete="tel" placeholder="+256 7xx xxx xxx" /></label><label>Job title<input name="job_title" defaultValue={user?.job_title} maxLength={100} placeholder="e.g. Store supervisor" /></label><label>Location<input name="location" defaultValue={user?.location} maxLength={150} placeholder="City or area" /></label></div></section>
    <section><h3>Account & platform role</h3><p id="identity-help">Users manage their own sign-in identity and password. For password help, ask them to use account recovery.</p><div className="person-fields"><label>Username<input value={user.username} readOnly aria-describedby="identity-help" /></label></div><label className="check"><input type="checkbox" name="is_active" defaultChecked={user?.is_active ?? true} />Account active</label>{profile.can_manage_admins && !user?.is_superuser && <label className="check"><input type="checkbox" name="platform_admin" defaultChecked={user?.platform_admin} />Platform administrator</label>}<p>Every active account can shop as a customer. Platform administrators manage all shops; shop roles below apply only to their assigned business and branch.</p></section>
    <section><h3>Shop roles</h3><Feedback error={shopError} />{access.map((row, i) => <div className="access-assignment" key={row.business}><strong>{shops.find(s => s.id === row.business)?.name || row.shop_name}</strong><div className="person-fields"><label>Role for {row.shop_name || row.business}<select value={row.role} onChange={e => updateAccess(i, { role: e.target.value as ShopAccess["role"] })}><option value="owner">Owner</option><option value="manager">Manager</option><option value="cashier">Cashier</option></select></label><label>Branch for {row.shop_name || row.business}<select value={row.branch} onChange={e => updateAccess(i, { branch: Number(e.target.value) })}>{shops.find(s => s.id === row.business)?.branches?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={row.active} onChange={e => updateAccess(i, { active: e.target.checked })} />Shop access active</label></div>)}<div className="person-toolbar"><label>Assign another shop<select value={newShop} onChange={e => setNewShop(e.target.value)}><option value="">Choose a shop</option>{shops.filter(s => !access.some(row => row.business === s.id) && s.branches?.length).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button type="button" className="secondary" disabled={!newShop} onClick={() => { const shop = shops.find(s => s.id === Number(newShop))!; setAccess(rows => [...rows, { business: shop.id, shop_name: shop.name, branch: shop.branches![0].id, role: "cashier", active: true }]); setChangedAccess(ids => [...ids, shop.id]); setNewShop(""); }}>Add shop role</button></div></section>
    {user && <p className="person-muted">Joined {user.date_joined ? new Date(user.date_joined).toLocaleDateString() : "—"} · Last sign-in {user.last_login ? new Date(user.last_login).toLocaleString() : "Not recorded"}</p>}
    <footer><button disabled={action.busy}>{action.busy ? "Saving…" : "Save account"}</button></footer>
  </fieldset>{protectedUser && <p>A superuser is required to edit this administrator.</p>}</form>;
}

export default function Users({ profile }: { profile: Profile }) {
  const [query, setQuery] = useState(""), [page, setPage] = useState(1), [editing, setEditing] = useState<User>(), [deleting, setDeleting] = useState<User>();
  const [confirmation, setConfirmation] = useState("");
  const state = useData<Page<User>>(`platform/users/?q=${encodeURIComponent(query)}&page=${page}`), action = useAction();
  return <div className="people-page"><header className="people-heading"><div><h1>Users and access</h1><p>Manage profiles, shop roles and platform permissions.</p></div><button className="secondary" onClick={() => void action.run(() => navigator.clipboard.writeText(`${window.location.origin}/signup`), "Registration link copied.")}><Icon name="copy" />Copy registration link</button></header>
    <section className="people-directory"><form className="account-search" role="search" aria-label="Search accounts" onSubmit={e => { e.preventDefault(); setQuery(formData(e.currentTarget).q.trim()); setPage(1); }}>
      <div className="account-search-control"><Icon name="search" /><input aria-label="Search accounts" title="Search by name, email, username or phone" name="q" type="search" placeholder="Search accounts…" /><button type="submit" aria-label="Search accounts">Search</button></div>
      <span className="account-count">{state.data?.count ?? "—"} <span>{state.data?.count === 1 ? "account" : "accounts"}</span></span>
    </form><Feedback {...state} /><Feedback {...action} />
    <div className="platform-table"><table className="people-table"><thead><tr><th>Person</th><th>Contact</th><th>Roles & access</th><th>Status</th><th className="person-actions-heading">Actions</th></tr></thead><tbody>{state.data?.results.map(user => { const protectedUser = (user.is_staff || user.is_superuser || user.platform_admin) && !profile.can_manage_admins; return <tr key={user.id}><td><div className="person-identity"><Avatar key={user.photo} user={user} /><div><strong>{[user.first_name, user.last_name].filter(Boolean).join(" ") || user.username}</strong><span>@{user.username}{user.job_title ? ` · ${user.job_title}` : ""}</span></div></div></td><td><span>{user.email || "No email added"}</span><small>{user.phone || user.location || "—"}</small></td><td><span className="person-badge">{user.is_superuser ? "Superuser" : user.platform_admin ? "Platform admin" : "Customer"}</span>{user.shop_access?.filter(a => a.active).map(a => <small key={a.business}>{a.shop_name} · {a.role} · {a.branch_name}</small>)}</td><td><span className={`person-status ${user.is_active ? "is-active" : ""}`}><i />{user.is_active ? "Active" : "Inactive"}</span></td><td><div className="person-row-actions"><button className="person-icon" aria-label={`Edit ${user.username}`} title="Edit user" disabled={protectedUser} onClick={() => setEditing(user)}><ActionIcon kind="edit" /></button><button className="person-icon danger" aria-label={`Delete ${user.username}`} title={user.id === profile.id ? "You cannot delete your own account" : "Delete user"} disabled={protectedUser || user.id === profile.id} onClick={() => { setConfirmation(""); setDeleting(user); }}><ActionIcon kind="delete" /></button></div></td></tr>; })}</tbody></table></div>{state.data?.count === 0 && <div className="people-empty"><h3>No accounts found</h3><p>Share the registration link, then find the user here after they sign up.</p></div>}<Pager data={state.data} page={page} setPage={setPage} /></section>
    {editing && <EditorDialog title={`Edit ${editing.username}`} onClose={() => setEditing(undefined)}><UserForm user={editing} profile={profile} onSaved={async () => { await state.reload(); setEditing(undefined); }} /></EditorDialog>}
    {deleting && <EditorDialog title={`Delete ${deleting.username}`} onClose={() => { if (!action.busy) setDeleting(undefined); }}><form className="person-form" onSubmit={e => { e.preventDefault(); void action.run(async () => { await api(`platform/users/${deleting.id}/`, { confirm_username: confirmation }, "DELETE"); setDeleting(undefined); if (page > 1) setPage(1); else await state.reload(); }, "Account deleted. Transaction history retained."); }}><Feedback {...action} /><p>This disables sign-in, removes all shop access and removes the account from this list. Orders, sales and audit history remain. The username stays reserved. Assign a replacement for any shop where this person is the last owner.</p><label>Type {deleting.username} to confirm<input value={confirmation} onChange={e => setConfirmation(e.target.value)} autoComplete="off" /></label><footer><button className="danger-button" disabled={action.busy || confirmation !== deleting.username}>Delete user</button></footer></form></EditorDialog>}
  </div>;
}
