from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-21 19:50
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ("notifications", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("delivered_at", models.DateTimeField(null=True)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("lease_until", models.DateTimeField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=100)),
                ("delivered_devices", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
