import { test, expect } from "@playwright/test";
const origin = process.env.API_DOCS_URL || "http://127.0.0.1:8000";
test("API documentation loads live endpoints, filters, links to Swagger and fits mobile", async ({ page }) => {
  await page.goto(origin + "/api/v1/docs/");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Great commerce.");
  await expect(page.locator(".endpoint").first()).toBeVisible();
  await page.getByRole("searchbox").fill("featured-products");
  await expect(page.locator(".endpoint")).toHaveCount(1);
  await expect(page.locator(".endpoint")).toContainText("GET");
  await page.getByRole("searchbox").fill("does-not-exist");
  await expect(page.getByText("No matching endpoints. Try another search.")).toBeVisible();
  await page.getByRole("searchbox").fill("");
  await expect.poll(() => page.locator("#directory").evaluate(el => el.clientHeight)).toBeLessThanOrEqual(540);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.screenshot({ path: "../docs/screenshots/api-documentation-desktop.png", fullPage: true });
  await page.locator(".endpoint").filter({ hasText: "featured-products" }).click();
  await expect(page.locator(".swagger-ui")).toBeVisible({ timeout: 45000 });
  await expect(page.locator(".opblock.is-open")).toContainText("featured-products");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(origin + "/");
  await page.getByRole("button", { name: "Menu" }).click();
  await expect(page.getByRole("navigation", { name: "Documentation" })).toBeVisible();
  await page.getByRole("button", { name: "Menu" }).click();
  await expect(page.getByRole("navigation", { name: "Documentation" })).not.toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("searchbox").fill("featured-products");
  await expect(page.locator(".endpoint")).toHaveCount(1);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.screenshot({ path: "../docs/screenshots/api-documentation-mobile.png", fullPage: true });
});
test("API documentation offers retry when the schema is unavailable", async ({ page }) => {
  let failed = true;
  await page.route("**/schema/?format=json", route => failed ? route.fulfill({ status: 503, body: "Unavailable" }) : route.continue());
  await page.goto(origin + "/api/v1/docs/");
  await expect(page.getByRole("button", { name: "Retry loading" })).toBeVisible();
  failed = false;
  await page.getByRole("button", { name: "Retry loading" }).click();
  await expect(page.locator(".endpoint").first()).toBeVisible();
});
