# Generated by Django 5.2.17 on 2026-09-19 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=20)),
                ("amount", models.PositiveBigIntegerField()),
                ("tendered", models.PositiveBigIntegerField()),
                ("change", models.PositiveBigIntegerField(default=0)),
                ("provider_verified", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
