# Generated by Django 5.2.17 on 2026-09-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="delivery_fee",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
