from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-23 13:45
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('businesses', '0004_business_suspended'),
        ('common', '0002_operation'),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name='audit',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='businesses.business'),
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DuukaYo', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('notice', models.CharField(blank=True, max_length=500)),
                ('orders_enabled', models.BooleanField(default=True)),
                ('shop_registration_enabled', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('manage_platform', 'Manage the DuukaYo platform')],
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='single_platform_settings')],
            },
        ),
    ]
