from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-19 20:45
import django.db.models.deletion
from django.db import migrations, models

import apps.orders.models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("businesses", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "token",
                    models.CharField(
                        default=apps.orders.models.capability,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("delivery", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("delivery_fee", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(max_length=3)),
                ("total", models.PositiveBigIntegerField()),
                ("lines", models.JSONField()),
                ("status", models.CharField(default="pending", max_length=15)),
                ("payment_state", models.CharField(default="unpaid", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="businesses.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="businesses.business",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "client_id"), name="unique_guest_order"
                    )
                ],
            },
        ),
    ]
