from typing import ClassVar

# Generated by Django 5.2.17 on 2026-09-21 19:53
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ("payments", "0001_initial"),
        ("sales", "0002_sale_delivery_fee"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=20)),
                ("amount", models.PositiveBigIntegerField()),
                ("tendered", models.PositiveBigIntegerField()),
                ("change", models.PositiveBigIntegerField(default=0)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("provider_verified", models.BooleanField(default=False)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
